### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by gjportegies** [Smile-SA/magento2-module-custom-entity#27]
Is it possible to update the php requirements to:
```"php": "~7.1.3||~7.2.0||~7.3.0"```

**Comment by romainruaud** [comment]
Hello @gjportegies 

This is not a read-only repository. 

Feel free to propose a PR for the changes you want. I think we can even get rid of any PHP requirements since Magento will handle them by himself.

Regards

**Comment by gjportegies** [comment]
Hello @romainruaud 

Thanks for the quick reply.
I will create a pull request for it. Indeed think removing the php requirements from the composer would be the way to go.
I'll check the other repo's as well, but closing this issue.
