### ISSUE TITLE
[M2 2.4.0] Can't save a new entity

### ISSUE THREAD

**Issue by adrian-sa** [Smile-SA/magento2-module-custom-entity#28]
Hello !

After installing the module on a Magento 2.4 and after some basic test, it seems that a new Entity can't be saved.

After clicking the save button, the following message appears : "Missing required argument $baseTmpPath of Magento\Catalog\Model\ImageUploader."

![Capture du 2020-09-23 15-11-03](https://user-images.githubusercontent.com/61878198/94016939-13b5b100-fdaf-11ea-9066-1ed1812ed8b4.png)

It seems to be related to the the dependency module: magento2-module-scoped-eav , since the ImageUploader class is instantiated in this module.

Maybe a dependency has changed when the constructor is called here: module-scoped-eav/Model/Entity/Attribute/Backend/Image.php

Thanks !

**Comment by romainruaud** [comment]
Please use `1.2.0` version that we just released, it should leverage to the latest `module-scoped-eav` version too.

Let us know

**Comment by adrian-sa** [comment]
The new versions fixed the problem indeed.

Thanks again !

**Comment by romainruaud** [comment]
Great I close then
