### ISSUE TITLE
Error using multiselect attribute.

### ISSUE THREAD

**Issue by francescorm** [Smile-SA/magento2-module-custom-entity#32]
When you add multiselect attribute and try to open an entity you will receive this error

1 exception(s):
Exception #0 (ReflectionException): Class  does not exist

Exception #0 (ReflectionException): Class  does not exist
<pre>#1 Magento\Framework\Code\Reader\ClassReader->getConstructor() called at [vendor/magento/framework/ObjectManager/Definition/Runtime.php:54]
#2 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/Validator/UniversalFactory.php:36]
#5 Magento\Framework\Validator\UniversalFactory->create() called at [vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php:642]
#6 Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/Modifier/Eav.php:273]
#7 Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav->setupAttributeMeta() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/Modifier/Eav.php:237]
#8 Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav->getContainerChildren() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/Modifier/Eav.php:213]
#9 Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav->addContainerChildren() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/Modifier/Eav.php:414]
#10 Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav->getAttributesMeta() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/Modifier/Eav.php:155]
#11 Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav->modifyMeta() called at [app/code/Smile/ScopedEav/Ui/DataProvider/Entity/Form/EntityDataProvider.php:74]
#12 Smile\ScopedEav\Ui\DataProvider\Entity\Form\EntityDataProvider->getMeta() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:330]
#13 Magento\Framework\View\Element\UiComponentFactory->mergeMetadata() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:231]
#14 Magento\Framework\View\Element\UiComponentFactory->create() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:140]
#15 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#16 Magento\Framework\View\Layout\Generator\UiComponent->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:93]
#17 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:365]
#18 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:68]
#19 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#20 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:65]
#21 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#22 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#23 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#24 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:293]
#25 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:47]
#26 Magento\Backend\Model\View\Result\Page->addBreadcrumb() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:32]
#27 Magento\Backend\Model\View\Result\Page\Interceptor->addBreadcrumb() called at [app/code/Smile/ScopedEav/Controller/Adminhtml/AbstractEntity.php:67]
#28 Smile\ScopedEav\Controller\Adminhtml\AbstractEntity->createActionPage() called at [app/code/Smile/ScopedEav/Controller/Adminhtml/Entity/NewAction.php:37]
#29 Smile\ScopedEav\Controller\Adminhtml\Entity\NewAction->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#30 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#31 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#32 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#33 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->___callPlugins() called at [generated/code/Smile/CustomEntity/Controller/Adminhtml/Entity/NewAction/Interceptor.php:23]
#35 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#36 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#37 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#38 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#39 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#40 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#41 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#42 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->___callPlugins() called at [generated/code/Smile/CustomEntity/Controller/Adminhtml/Entity/NewAction/Interceptor.php:32]
#43 Smile\CustomEntity\Controller\Adminhtml\Entity\NewAction\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#44 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#45 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#46 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#47 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#48 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#49 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#50 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#51 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#52 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

**Comment by jubalin** [comment]
I'm having the same problem. Did you find a fix for this?

**Comment by francescorm** [comment]
Hi there, no i'm sorry but i have plan to check it.

**Comment by jublm** [comment]
I got a fix for this. I've overridden \Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav in a custom module until the module is updated, it'w working fine. This is my fix:

`<?php

namespace W2e\SmileEntityOverride\Ui\DataProvider\Entity\Form\Modifier;

use Magento\Catalog\Model\Category\FileInfo;
use Magento\Catalog\Model\ResourceModel\Eav\Attribute as EavAttribute;
use Magento\Catalog\Model\ResourceModel\Eav\AttributeFactory as EavAttributeFactory;
use Magento\Ui\Component\Form\Element\Wysiwyg as WysiwygElement;
use Magento\Ui\Component\Form\Field;
use Smile\ScopedEav\Api\Data\AttributeInterface;

class Eav extends \Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Eav
{
    /**
     * @var Helper\Eav
     */
    private $eavHelper;

    /**
     * @var \Smile\ScopedEav\Model\Locator\LocatorInterface
     */
    private $locator;

    /**
     * @var \Magento\Framework\Stdlib\ArrayManager
     */
    private $arrayManager;

    /**
     * @var \Smile\ScopedEav\Ui\DataProvider\Entity\Form\EavValidationRules
     */
    private $validationRules;

    /**
     * @var \Magento\Framework\App\Request\DataPersistorInterface
     */
    private $dataPersistor;

    /**
     * @var array
     */
    private $bannedInputTypes;

    /**
     * @var array
     */
    private $attributesToEliminate;

    /**
     * @var array
     */
    private $attributesToDisable;

    /**
     * @var FileInfo
     */
    private $fileInfo;

    /**
     * internal cache for attribute models
     * @var array
     */
    private $attributesCache = [];

    /**
     * @var EavAttributeFactory
     * @since 101.0.0
     */
    protected $eavAttributeFactory;

    /**
     * Constructor.
     *
     * @param \Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Helper\Eav $eavHelper             EAV helper.
     * @param \Smile\ScopedEav\Model\Locator\LocatorInterface                  $locator               Entity locator.
     * @param \Magento\Framework\Stdlib\ArrayManager                           $arrayManager          Array manager.
     * @param \Smile\ScopedEav\Ui\DataProvider\Entity\Form\EavValidationRules  $validationRules       EAV validation rules
     * @param \Magento\Framework\App\Request\DataPersistorInterface            $dataPersistor         Data persistor.
     * @param EavAttributeFactory                                              $eavAttributeFactory
     * @param FileInfo                                                         $fileInfo              File information.
     * @param array                                                            $bannedInputTypes      Input types removed from the form.
     * @param array                                                            $attributesToEliminate Attribute codes removed from the form.
     * @param array                                                            $attributesToDisable   Attribute codes to be disabled.
     */
    public function __construct(
        \Smile\ScopedEav\Ui\DataProvider\Entity\Form\Modifier\Helper\Eav $eavHelper,
        \Smile\ScopedEav\Model\Locator\LocatorInterface $locator,
        \Magento\Framework\Stdlib\ArrayManager $arrayManager,
        \Smile\ScopedEav\Ui\DataProvider\Entity\Form\EavValidationRules $validationRules,
        \Magento\Framework\App\Request\DataPersistorInterface $dataPersistor,
        EavAttributeFactory $eavAttributeFactory,
        FileInfo $fileInfo,
        array $bannedInputTypes = [],
        array $attributesToEliminate = [],
        array $attributesToDisable = []
    ) {
        $this->eavHelper             = $eavHelper;
        $this->locator               = $locator;
        $this->arrayManager          = $arrayManager;
        $this->bannedInputTypes      = $bannedInputTypes;
        $this->validationRules       = $validationRules;
        $this->dataPersistor         = $dataPersistor;
        $this->attributesToEliminate = $attributesToEliminate;
        $this->attributesToDisable   = $attributesToDisable;
        $this->fileInfo = $fileInfo;
        $this->eavAttributeFactory = $eavAttributeFactory;
        parent::__construct($eavHelper, $locator, $arrayManager, $validationRules, $dataPersistor, $fileInfo);
    }

    /**
     * Retrieve attribute meta config.
     *
     * @param AttributeInterface $attribute Attribute.
     * @param string             $groupCode Attribute group code.
     * @param int                $sortOrder Sort order.
     *
     * @return array
     */
    public function setupAttributeMeta(AttributeInterface $attribute, $groupCode, $sortOrder)
    {
        $configPath = static::META_CONFIG_PATH;

        $meta = $this->arrayManager->set($configPath, [], [
            'dataType'    => $attribute->getFrontendInput(),
            'formElement' => $this->eavHelper->getFormElement($attribute->getFrontendInput()),
            'visible'     => true,
            'required'    => $attribute->getIsRequired(),
            'notice'      => $attribute->getNote(),
            'default'     => $attribute->getDefaultValue(),
            'label'       => $attribute->getDefaultFrontendLabel(),
            'code'        => $attribute->getAttributeCode(),
            'source'      => $groupCode,
            'scopeLabel'  => $this->getScopeLabel($attribute),
            'globalScope' => $this->isScopeGlobal($attribute),
            'sortOrder'   => $sortOrder * self::SORT_ORDER_MULTIPLIER,
        ]);

        $attributeModel = $this->getAttributeModel($attribute);
        if ($attributeModel->usesSource()) {
            $source = $attributeModel->getSource();
            $options = $source->getAllOptions();
            $meta = $this->arrayManager->merge($configPath, $meta, ['options' => $this->convertOptionsValueToString($options)]);
        }

        if ($this->canDisplayUseDefault($attribute)) {
            $meta = $this->arrayManager->merge($configPath, $meta, ['service' => ['template' => 'ui/form/element/helper/service']]);
        }

        if (!$this->arrayManager->exists($configPath . '/componentType', $meta)) {
            $meta = $this->arrayManager->merge($configPath, $meta, ['componentType' => Field::NAME]);
        }

        if (in_array($attribute->getAttributeCode(), $this->attributesToDisable)) {
            $meta = $this->arrayManager->merge($configPath, $meta, ['disabled' => true]);
        }

        $childData = $this->arrayManager->get($configPath, $meta, []);
        if (($rules = $this->validationRules->build($attribute, $childData))) {
            $meta = $this->arrayManager->merge($configPath, $meta, ['validation' => $rules]);
        }

        $meta = $this->addUseDefaultValueCheckbox($attribute, $meta);

        switch ($attribute->getFrontendInput()) {
            case 'boolean':
                $meta = $this->customizeCheckbox($attribute, $meta);
                break;
            case 'textarea':
                $meta = $this->customizeWysiwyg($attribute, $meta);
                break;
            case 'image':
                $meta = $this->customizeImage($attribute, $meta);
                break;
        }

        return $meta;
    }

    /**
     * Convert options value to string.
     *
     * @param array $options
     * @return array
     */
    private function convertOptionsValueToString(array $options) : array
    {
        array_walk(
            $options,
            function (&$value) {
                if (isset($value['value']) && is_scalar($value['value'])) {
                    $value['value'] = (string)$value['value'];
                }
            }
        );

        return $options;
    }

    private function getAttributeModel($attribute)
    {
        // The statement below solves performance issue related to loading same attribute options on different models
        if ($attribute instanceof EavAttribute) {
            return $attribute;
        }
        $attributeId = $attribute->getAttributeId();

        if (!array_key_exists($attributeId, $this->attributesCache)) {
            $this->attributesCache[$attributeId] = $this->eavAttributeFactory->create()->load($attributeId);
        }

        return $this->attributesCache[$attributeId];
    }

    /**
     * Check if attribute scope is global.
     *
     * @param AttributeInterface $attribute Attribute.
     *
     * @return bool
     */
    private function isScopeGlobal(AttributeInterface $attribute)
    {
        return $this->eavHelper->isScopeGlobal($attribute);
    }

    /**
     * Whether attribute can have default value.
     *
     * @param AttributeInterface $attribute Attribute.
     *
     * @return bool
     */
    private function canDisplayUseDefault(AttributeInterface $attribute)
    {
        return $this->eavHelper->canDisplayUseDefault($attribute, $this->locator->getEntity());
    }

    /**
     * Retrieve attribute scope label.
     *
     * @param AttributeInterface $attribute Attribute.
     *
     * @return \Magento\Framework\Phrase|string
     */
    private function getScopeLabel(AttributeInterface $attribute)
    {
        return $this->eavHelper->getScopeLabel($attribute);
    }

    /**
     * Append a use default value if needed.
     *
     * @param AttributeInterface $attribute Attribute.
     * @param array              $meta      Attribute meta.
     *
     * @return array
     */
    private function addUseDefaultValueCheckbox(AttributeInterface $attribute, array $meta)
    {
        $canDisplayService = $this->canDisplayUseDefault($attribute);

        if ($canDisplayService) {
            $storeId = $this->locator->getStore()->getId();
            $entity  = $this->locator->getEntity();
            $meta['arguments']['data']['config']['service'] = ['template' => 'ui/form/element/helper/service'];
            $meta['arguments']['data']['config']['disabled'] = !$this->eavHelper->hasValueForStore($entity, $attribute, $storeId);
        }

        return $meta;
    }

    /**
     * Add wysiwyg properties.
     *
     * @param AttributeInterface $attribute Attribute.
     * @param array              $meta      Meta data of data provider.
     *
     * @return array
     */
    private function customizeWysiwyg(AttributeInterface $attribute, array $meta)
    {
        if (!$attribute->getIsWysiwygEnabled()) {
            return $meta;
        }

        $meta['arguments']['data']['config']['formElement'] = WysiwygElement::NAME;
        $meta['arguments']['data']['config']['wysiwyg'] = true;
        $meta['arguments']['data']['config']['wysiwygConfigData'] = [
            'add_variables' => false,
            'add_widgets' => false,
            'add_directives' => true,
            'use_container' => true,
            'container_class' => 'hor-scroll',
        ];

        return $meta;
    }

    /**
     * Customize checkboxes.
     *
     * @param AttributeInterface $attribute Attribute.
     * @param array              $meta      Metadata of data provider.
     *
     * @return array
     */
    private function customizeCheckbox(AttributeInterface $attribute, array $meta)
    {
        if ($attribute->getFrontendInput() === 'boolean') {
            $meta['arguments']['data']['config']['prefer'] = 'toggle';
            $meta['arguments']['data']['config']['valueMap'] = [
                'true' => '1',
                'false' => '0',
            ];
        }

        return $meta;
    }

    /**
     * Customize image field.
     *
     * @param AttributeInterface $attribute Attribute.
     * @param array              $meta      Current metadata of data provider.
     *
     * @return array
     */
    private function customizeImage(AttributeInterface $attribute, array $meta)
    {
        if ($attribute->getFrontendInput() !== 'image') {
            return $meta;
        }
        $meta['arguments']['data']['config']['formElement'] = 'fileUploader';
        $meta['arguments']['data']['config']['allowedExtensions'] = 'jpg jpeg gif png';
        $meta['arguments']['data']['config']['elementTmpl'] = 'ui/form/element/uploader/image';
        $meta['arguments']['data']['config']['uploaderConfig'] = [
            'url' => 'scoped_eav/entity/image_upload',
        ];

        return $meta;
    }
}
`

**Comment by cemag44300** [comment]
Thank you @jublm i will push a new release this morning
