### ISSUE TITLE
Error on Magento 2.4.5 - Installing schema... Smile\ScopedEav\Setup\SchemaSetup::getEntityWebsiteTable():

### ISSUE THREAD

**Issue by redingopl** [Smile-SA/magento2-module-custom-entity#45]
During the set:up we have error:

`Module 'Smile_CustomEntity':
Installing schema... Smile\ScopedEav\Setup\SchemaSetup::getEntityWebsiteTable(): Return value must be of type Smile\ScopedEav\Setup\SchemaSetup, Magento\Framework\DB\Ddl\Table returned#0 /var/www/virtual/website/htdocs/vendor/smile/module-custom-entity/Setup/InstallSchema.php(77): Smile\ScopedEav\Setup\SchemaSetup->getEntityWebsiteTable()`

<img width="2054" alt="image" src="https://user-images.githubusercontent.com/23629805/189297330-a56db277-269b-4550-a28e-53be35b66923.png">

**Comment by jesperbrejning** [comment]
Hi, I get the same error when installing on M2.4.5. 

Have you solved the issue?

**Comment by johanroberthson** [comment]
Hi,
Same error for M2.4.4.
Its possible to install with following changes:
 /**
     * Prepare a website assigment table for an entity.
     *
     * @param string $entityTableName Entity table name.
     *
     * @return Table
     */
    public function getEntityWebsiteTable(string $entityTableName): Table
instead of this:
 /**
     * Prepare a website assigment table for an entity.
     *
     * @param string $entityTableName Entity table name.
     *
     * @return $this
     */
    public function getEntityWebsiteTable(string $entityTableName): self
  
In SchemaSetup.php in mdule-scoped-eav

**Comment by cemag44300** [comment]
Thank you for your return @johanroberthson

**Comment by cemag44300** [comment]
Thank you @johanroberthson  i will push a new release this morning

**Comment by cemag44300** [comment]
https://github.com/Smile-SA/magento2-module-scoped-eav/releases/tag/1.3.5
