### ISSUE TITLE
Saving store specific override also sets url_key to null

### ISSUE THREAD

**Issue by mdevrees** [Smile-SA/magento2-module-custom-entity#59]
When switching to a specific store view, change a setting like Description and then saving the Custom Entity, there is also an entity created for url_key override.

Steps to reproduce:
1. Create an entity and open it, changing storeview in the topleft corner
2. Uncheck Use Default Value and change a value, in my screenshot below I changed description:
![image](https://github.com/Smile-SA/magento2-module-custom-entity/assets/1950480/b0682af2-5758-456d-a283-95476e0ba81e)
3. Save the Custom Entity and see the URL key being empty:
![image](https://github.com/Smile-SA/magento2-module-custom-entity/assets/1950480/09789f7e-63e5-405c-88f7-f8be6ddef36e)

The database also contains a NULL value for the url key:
![image](https://github.com/Smile-SA/magento2-module-custom-entity/assets/1950480/a8e94cc4-f93c-4ca2-b7a6-8af1b7247fa3)

**Comment by cemag44300** [comment]
Hello @mdevrees 

I can't reproduce on 1.3.12 version of the module.
What version of custom entity is installed on your project ?

`MariaDB [magento2]> select * from smile_custom_entity_varchar where attribute_id = 181;
+----------+--------------+----------+-----------+--------------------------------------------+
| value_id | attribute_id | store_id | entity_id | value                                      |
+----------+--------------+----------+-----------+--------------------------------------------+
|       11 |          181 |        0 |         5 | test0                                      |
|       12 |          181 |        1 |         5 | test1                                      |
|       13 |          181 |        2 |         5 | test2                                      |
+----------+--------------+----------+-----------+--------------------------------------------+
`

**Comment by ldrooij** [comment]
This happens for me in version 1.3.12. Please note that this happens when 'Use default value' is left checked for 'URL key' and the entity is save with a store scope.

**Comment by mdevrees** [comment]
Hi @cemag44300 
The version this was tested on, was 1.3.11 but is also reproducible on 1.3.12. 
It is used in combination with Magento version 2.4.3-p1, not sure of in a newer release some changes were made specifically to saving url_key.
